---
driver:
  name: docker
  use_sudo: false
  provision_command:
    - apt-get update
    - apt-get install -y curl wget net-tools

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: 'test/integration/encrypted_data_bag_secret'

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: debian-8

suites:
  - name: default
    run_list:
      - recipe[np-users::default]
    attributes:
      users:
        - nick
        - rsaxvc
      np_users:
        dotfiles:
          repos:
            nick:
              - repo: https://github.com/nickpegg/dotfiles
                branch: master
