name 'np-users'
maintainer 'Nick Pegg'
maintainer_email 'nick@nickpegg.com'
license 'MIT'
description 'Sets up users'
version '0.3.3'

source_url 'https://github.com/nickpegg/cookbook-np-users'
issues_url 'https://github.com/nickpegg/cookbook-np-users/issues'

supports 'arch'
supports 'debian', '~> 11.0'
supports 'fedora', '= 39'
supports 'ubuntu', '= 20.04'
supports 'ubuntu', '= 22.04'
