name 'np-users'
maintainer 'Nick Pegg'
maintainer_email 'nick@nickpegg.com'
license 'all_rights'
description 'Sets up users'
long_description 'Sets up users'
version '0.1.6'

depends 'apt'
depends 'user', '~> 0.4.2'
depends 'python', '~> 1.4.6'

supports 'debian', '~> 8.0'
supports 'ubuntu', '= 14.04'
supports 'ubuntu', '= 16.04'
